---
- name: Check if OAuth app '{{ oauth_app.name }}' already exists
  set_fact:
    oauth_app_exists: >-
      {{
        get_apps_response.json is defined and
        (get_apps_response.json | selectattr('name', 'equalto', oauth_app.name)
        | selectattr('redirect_uri', 'equalto', oauth_app.redirect_uri)
        | list | length) > 0
      }}

- name: Create OAuth application '{{ oauth_app.name }}' if not exists
  uri:
    url: "https://{{ ocp4_workload_platform_engineering_workshop_gitlab_config_host }}/api/v4/applications"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ _ocp4_workload_platform_engineering_workshop_gitlab_root_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ oauth_app.name }}"
      redirect_uri: "{{ oauth_app.redirect_uri }}"
      scopes: "{{ oauth_app.scopes }}"
      trusted: true
    status_code: 201
  when: not oauth_app_exists
  register: oauth_app_create_response
  
- name: Store OAuth app details in persistent fact
  set_fact:
    _gitlab_oauth_apps: "{{ _gitlab_oauth_apps | default({}) | combine({oauth_app.name: app_details}) }}"
  vars:
    app_details:
      application_id: "{{ oauth_app_create_response.json.application_id if not oauth_app_exists else existing_oauth_app.application_id }}"
      secret: "{{ oauth_app_create_response.json.secret if not oauth_app_exists else existing_oauth_app.secret | default('SECRET_NOT_AVAILABLE') }}"
      name: "{{ oauth_app.name }}"
      redirect_uri: "{{ oauth_app.redirect_uri }}"
      trusted: "{{ oauth_app.trusted | default(false) }}"

- name: Show app creation output for '{{ oauth_app.name }}'
  debug:
    msg: >-
      {% if oauth_app_create_response is defined and oauth_app_create_response.json is defined %}
        Created '{{ oauth_app.name }}' - App ID: {{ oauth_app_create_response.json.application_id }}, Secret: {{ oauth_app_create_response.json.secret }}
      {% elif oauth_app_exists %}
        OAuth app '{{ oauth_app.name }}' already exists. Skipping creation.
      {% else %}
        Unknown state for '{{ oauth_app.name }}'.
      {% endif %}