---
- name: Create GitLab application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'gitlab/gitlab-application.yml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: gitlab_result
  until: gitlab_result is not failed

- name: Print gitlab_result from the previous task
  ansible.builtin.debug:
    var: gitlab_result

- name: Retrieve Gitlab root private token
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: root-user-personal-token
    namespace: "{{ ocp4_workload_platform_engineering_workshop_gitlab_namespace }}"
  register: r_root_token
  retries: 120
  delay: 10
  ignore_errors: true
  until:
    - r_root_token is defined
    - r_root_token.resources is defined
    - r_root_token.resources | length > 0
    - r_root_token.resources[0] is defined
    - r_root_token.resources[0].data is defined
    - r_root_token.resources[0].data.token is defined
    - r_root_token.resources[0].data.token | length > 0

- name: Decode root token
  ansible.builtin.set_fact:
    _ocp4_workload_platform_engineering_workshop_gitlab_root_token: "{{ r_root_token.resources[0].data.token | b64decode }}"

- name: Get list of existing OAuth apps
  uri:
    url: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_host }}/api/v4/applications"
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ _ocp4_workload_platform_engineering_workshop_gitlab_root_token }}"
    return_content: yes
    status_code: 200
  register: get_apps_response
  failed_when: false
  changed_when: false

- name: Process OAuth applications
  include_tasks: create_oauth_app.yml
  loop: "{{ ocp4_workload_platform_engineering_workshop_gitlab_oauth_apps }}"
  loop_control:
    loop_var: oauth_app