---

- name: Create vault secret for stackrox
  kubernetes.core.k8s_exec:
    namespace: "{{ ocp4_workload_platform_engineering_workshop_vault_namespace }}"
    pod: vault-0
    command: "vault kv put kv/secrets/rhdh/stackrox token={{
     ocp4_workload_platform_engineering_workshop_stackrox_token }}"

- name: Create vault secret for common password
  kubernetes.core.k8s_exec:
    namespace: "{{ ocp4_workload_platform_engineering_workshop_vault_namespace }}"
    pod: vault-0
    command: "vault kv put kv/secrets/rhdh/common_password password={{
     common_password }}"

- name: Create vault secrets for Quay access
  vars:
    quay_auth: "{{ ocp4_workload_platform_engineering_workshop_quay_admin_user }}:{{ ocp4_workload_platform_engineering_workshop_quay_admin_user_password }}"
  kubernetes.core.k8s_exec:
    namespace: "{{ ocp4_workload_platform_engineering_workshop_vault_namespace }}"
    pod: vault-0
    command: "{{ item }}"
  loop:
    - 'vault kv put kv/secrets/rhdh/registry/auth value={{ quay_auth | b64encode }}'
    - "vault kv put kv/secrets/rhdh/registry/username value={{ ocp4_workload_platform_engineering_workshop_quay_admin_user }}"
    - "vault kv put kv/secrets/rhdh/registry/password value={{ ocp4_workload_platform_engineering_workshop_quay_admin_user_password }}"