---

- name: Install Workshop
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: "Install Infra Cluster"
      ansible.builtin.include_role:
        name: ocp4_workload_platform_engineering_workshop_infra_cluster
      vars:
        ACTION: create